create database customer_behaviour;

use customer_behaviour;

select * from mytable limit 20;

-- what is the total revenue generated by male vs female customers--
select gender,sum(purchase_amount) from mytable
group by gender;

-- which customer used discount and still spent more than the avergae purchace amount --
select customer_id,purchase_amount from mytable
where discount_applied = 'yes' AND  purchase_amount >= (select AVG(purchase_amount) from mytable);

-- which are the top 5 products with the highest average review rating--
select item_purchased, ROUND(AVG(review_rating),2) as average_product_rating
from mytable
group by item_purchased 
order by AVG(review_rating) desc
LIMIT 5;

-- compare the average purchase anounts between standard and express shipping --
select shipping_type, AVG( purchase_amount) from mytable
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- do subscribed customers spend more? compare average spend and total spend between subcribers and non subscribers --
select subscription_status,
count(customer_id) as total_cust,
ROUND(AVG(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by avg_spend, total_revenue;

-- which 5 products have the highest percentage of purchases with discount applied--
select item_purchased, 
round(100* sum(case when discount_applied='yes' then 1 else 0 end)/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- segement customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment -- 

with customer_type as ( 
  select customer_id, previous_purchases,
  case 
    when previous_purchases =1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
end as customer_segment
from mytable
)

select customer_segment, count(*) as NUmber_of_customers
from customer_type 
group by customer_segment;
			
-- what are the top 3 most purchased products within each category -- 
with item_counts as (
select category,  item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)            
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe --
select subscription_status, count(customer_id) as repeat_buyers
from mytable 
where previous_purchases > 5 
group by subscription_status;

-- what is the revenue contribution of each age group -- 
select age_group, sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;







	
























